project_id = "dkccadwohifcqcdzhhnu"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "200MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://vita-9672hiaw6-mordechaipotashs-projects.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
